<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSessionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sessions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->bigInteger('user_id')->comment("User ID Who Create this Session");
            $table->string('status')->comment("status use constant" . TRAINING_SESSION_COMPLETED . " and " . TRAINING_SESSION_UPCOMING);
            $table->string('name', 200)->comment("Session name");
            $table->string('type')->comment("Session Type");
            $table->string('intensity')->comment("Session Type");
            // $table->timestamp('date')->comment("Session date and time"); 
            $table->integer('fees')->comment("Session fee amount");
            $table->string('professional_name')->comment("Session Professional name");
            $table->string('session_id')->comment("Autogenerated Session id with prefix");
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sessions');
    }
}
